Xiq 1219 cli delta update (#397)
* Create onboarding.py

* tests

* new_path

* new_folder_v2

* folder name change

* test_dragos

* Update test1_dragos.py

* save_config

* Update test1_raluca.py

* Update test1_dragos.py

* Create test1_raluca.py

* Update test1_dragos.py

* delete

* Update test1_dragos.py

* Update test1_dragos.py

* commit

* Update test1_dragos.py

* test1_devi.py

* Update test1_dragos.py

* Update test1_dragos.py

* Update test1_dragos.py

* test_update

* replaced self into cls and updated iqagent config

* test1_dragos

* Update test1_dragos.py

* beta_test

* Create test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

new commit

* update_adjustments

* delete_old_files

* Delete slm_5520_exos.yaml

* commit

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update slm_5520_rack1_2_exos.yaml

* Delete slm_5520_rack1_2_exos.yaml

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update topo.test.g2r1.yaml

* Update slm_5420_rack2_1_voss.yaml

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update topo.test.g2r1.yaml

* Update slm_5420_rack2_1_voss.yaml

* Create slm_5520_rack1_2_exos.yaml

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* new_update

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

Observed script failure in stack , due to save_stack_template() missing 1 required positional argument


Detected Exception: Traceback (most recent call last):
  File "/git/extreme_automation_tests/Tests/Pytest/NonProduction/XIQ/Wired/Device_Management/Device_360/Configuration/General/Cli_Delta_Update_XIQ1219/TestCases/test_xiq_1219_clideltaupdate.py", line 495, in setup_class
    cls.xiq.xflowsconfigureSwitchTemplate.save_stack_template()
TypeError: save_stack_template() missing 1 required positional argument: 'sw_template_name'

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

* Update test_xiq_1219_clideltaupdate.py

Co-authored-by: deviranganathan <dranganathan@extremenetworks.com>
Co-authored-by: rcionca <rcionca@extremenetworks.com>
Co-authored-by: zoicanionut <dzoican@extremenetworks.com>
Co-authored-by: Rajesh Ganapathi <78551821+raganapathi@users.noreply.github.com>